math:
	../../tools/JackCompiler.sh MathTest

output:
	../../tools/JackCompiler.sh OutputTest

screen:
	../../tools/JackCompiler.sh ScreenTest

pongTest:
	../../tools/JackCompiler.sh Pong

array:
	../../tools/JackCompiler.sh ArrayTest

string:
	../../tools/JackCompiler.sh StringTest

sys:
	../../tools/JackCompiler.sh SysTest

memory:
	../../tools/JackCompiler.sh MemoryTest

keyboard:
	../../tools/JackCompiler.sh KeyboardTest